Make verbosity an optional field for a log type entry
y-scope/clp pull request #145
Opened 2023-07-28 03:06 UTC by wraymo

# Description

Verbosity is a required field for a log type entry since the majority of unstructured logs have such information. However, in the case of semi-structured logs, this information is typically stored in a dedicated field (e.g., `level`), and the actual log text does not include it. Making it an optional field ensures future compatibility.

# Validation performed

2023-08-02 10:45 UTC, kirkrodrigues commented
A few concerns:
* What's the performance impact of this change given that we're introducing a branch?
* We shouldn't rely on the code knowing what type of dictionary is on disk. Instead, we should encode some metadata into the dictionary so that readers can determine whether each entry will contain a verbosity or not.
* The current verbosity detection in the code is very rudimentary and in reality we don't use the verbosity anywhere else in the code. I think in the future, we'll rely on the verbosity being parsed by the schema-based parser and it would be a kind of variable value. We'll also be able to get the verbosity directly from our logging libraries.

So for now, I would actually suggest removing the verbosity from the dictionary entirely.

2023-08-02 21:13 UTC, wraymo commented
> A few concerns:
> 
> * What's the performance impact of this change given that we're introducing a branch?
> * We shouldn't rely on the code knowing what type of dictionary is on disk. Instead, we should encode some metadata into the dictionary so that readers can determine whether each entry will contain a verbosity or not.
> * The current verbosity detection in the code is very rudimentary and in reality we don't use the verbosity anywhere else in the code. I think in the future, we'll rely on the verbosity being parsed by the schema-based parser and it would be a kind of variable value. We'll also be able to get the verbosity directly from our logging libraries.
> 
> So for now, I would actually suggest removing the verbosity from the dictionary entirely.

Updated

2023-08-06 21:52 UTC, kirkrodrigues approved these changes

2023-08-06 21:55 UTC, kirkrodrigues commented
After an offline discussion we decided to remove the verbosity field from the logtype dictionary (at least for now) because:
* The verbosity was being stored but was never used anywhere in the code
* The heuristics for detecting a verbosity only apply to a subset of possible log formats
* The verbosity was being searched for/parsed using an expensive process (we will parse it using the schema-based parser in the future)

2023-08-06 21:56 UTC, kirkrodrigues requested changes
Sorry, forgot that we need to bump the format version (`streaming_archive::cArchiveFormatVersion`) since the logtype dictionary format has changed.

2023-08-07 02:05 UTC, kirkrodrigues approved these changes

2023-08-07 02:26 UTC, merged