Add mongocxx dependencies to all dev environments
y-scope/clp pull request #218
Opened 2024-01-05 23:56 UTC by gibber9809

# Description
This PR adds mongocxx dependencies to each dev environment. These changes have been separated out from the following PR for the reducer so that we can update the environment used by the CI.

# Validation performed
- validated that reducer builds successfully in ubuntu focal, ubuntu jammy, and centos7.4 docker containers
- unable to validate build on macos

2024-01-06 02:00 UTC, kirkrodrigues requested changes

2024-01-07 23:27 UTC, gibber9809 commented on components/core/tools/scripts/lib_install/mongoc.sh
> +${install_command_prefix} cmake --build . --target install
Ended up doing this slightly differently because this code will attempt to run the command "" if the privileged prefix isn't set.

2024-01-08 02:46 UTC, kirkrodrigues commented
Centos build failure unrelated to PR. Caused by https://github.com/boostorg/boost/issues/842. That said, we should add `set -e` to the install scripts so that they terminate earlier on error.

2024-01-08 02:46 UTC, kirkrodrigues approved these changes

2024-01-08 02:51 UTC, gibber9809 reviewed
minor refactors lgtm

2024-01-08 03:02 UTC, merged