Run rabbitmq in a separate container; Use the execution container from github
y-scope/clp pull request #26
Opened 2021-10-30 03:43 UTC by kirkrodrigues

2021-11-02 03:29 UTC, NamanGulati approved these changes
LGTM

2021-11-09 07:22 UTC, jackluo923 requested changes
Small changes required.

2021-11-09 07:22 UTC, jackluo923 commented on components/package-template/src/sbin/start-clp
> +        f.write(f"listeners.tcp.default = {clp_config.scheduler_queue.port}\n")
Switch to single quotes

2021-11-09 07:36 UTC, jackluo923 approved these changes

2021-11-09 07:36 UTC, merged