clp-s: Add case-insensitive search
y-scope/clp pull request #272
Opened 2024-02-09 18:22 UTC by wraymo

# References

# Description

# Validation performed

`msg: "Initialized Wire Specification"` and `c: repl`

2024-02-09 23:25 UTC, kirkrodrigues requested changes
Can we also add an example to the docs?

2024-02-11 02:30 UTC, wraymo commented
> Can we also add an example to the docs?

Do I need to add examples for both clp and clp-s? Add this option to an existing example, or create a new one?

2024-02-11 02:33 UTC, kirkrodrigues commented
> Do I need to add examples for both clp and clp-s? Add this option to an existing example, or create a new one?

Good point. Yeah, we should probably add an example for both clp and clp-s.

2024-02-12 01:39 UTC, wraymo commented
> > Do I need to add examples for both clp and clp-s? Add this option to an existing example, or create a new one?
> 
> Good point. Yeah, we should probably add an example for both clp and clp-s.

But for clp, a lot of options are not shown with an example in the doc. If we want to add this one, what about `compression-level`, `target-encoded-file-size`, `remove-path-prefix`, etc?

2024-02-12 01:53 UTC, kirkrodrigues commented
> But for clp, a lot of options are not shown with an example in the doc. If we want to add this one, what about `compression-level`, `target-encoded-file-size`, `remove-path-prefix`, etc?

I think `--ignore-case` would probably be the most used option out of all the ones you mentioned since folks would forget to use capitals when entering a query. It's also a hint to users that by default the query is case-sensitive.

2024-02-12 01:58 UTC, kirkrodrigues commented
Fwiw, we should indeed document all the other parameters, but that will be in another reference doc once we have the rest of CLP's docs set up online.

2024-02-12 18:35 UTC, kirkrodrigues requested changes

2024-02-12 18:35 UTC, kirkrodrigues commented on components/core/src/clp_s/clp-s.cpp
> -    return 0;
Why delete this?

2024-02-12 18:35 UTC, kirkrodrigues commented on docs/core/clp-structured.md
> +the compressed data:**
```suggestion
**Find FATAL or ERROR log events and ignore case distinctions between values in the query and the
compressed data:**
```

2024-02-12 18:35 UTC, kirkrodrigues commented on docs/core/clp-unstructured.md
> +in the query and the compressed data:**
```suggestion
**Search `/mnt/data/archives1` for specific ERROR logs and ignore case distinctions:**
```

2024-02-12 18:56 UTC, wraymo commented on components/core/src/clp_s/clp-s.cpp
> -    return 0;
It's by mistake

2024-02-12 21:52 UTC, kirkrodrigues approved these changes
Commit msg: `Add support for case-insensitive searches in clp-s and the package. (#272)`?

2024-02-12 22:05 UTC, merged