Add case sensitivity option to search controls; Fix incorrect logger debug message in `StatsCollectionName`.
y-scope/clp pull request #280
Opened 2024-02-13 07:10 UTC by junhaoliao

# References
1. Search option `ignore_case` was recently added for `clp-s`. 

# Description
1. Add case sensitivity option to search controls.
2. Fix incorrect logger debug message in `StatsCollectionName`.

# Validation performed
1. Loaded Web UI in a browser.
2. In the search controls, observed that `Case sensitivity: Insensitive` as the default option. 
3. With `hadoop-24hrs/logs/i-00c90a0f/` compressed, in the Web UI searched with keyword "downloading", `Time Range` as `All Time`, and `Case sensitivity: Insensitive`, and observed "Results count: 376".
4. In the search controls, changed `Case sensitivity` to be `Sensitive` and restarted the search. Observed "Results count: 0".

2024-02-13 07:13 UTC, junhaoliao commented
Does it make more sense to place "Insensitive" (the default setting) on the left instead?

![image](https://github.com/y-scope/clp/assets/43196707/5b6da701-db39-467b-a3d6-8e59453dc527)

2024-02-13 12:37 UTC, kirkrodrigues commented
> Would it make more sense to place "Insensitive" (the default setting) on the left instead?

Sounds good.

2024-02-13 12:38 UTC, kirkrodrigues requested changes
Can we set a max-width (or some other solution) for the column labels so that they don't expand too much like this?

![image](https://github.com/y-scope/clp/assets/2454684/e2d7cbe3-a727-44e1-ac86-fb6d8e7a20d5)

2024-02-13 19:07 UTC, junhaoliao commented
> Can we set a max-width (or some other solution) for the column labels so that they don't expand too much like this?
> 
> ![image](https://private-user-images.githubusercontent.com/2454684/304409776-e2d7cbe3-a727-44e1-ac86-fb6d8e7a20d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTEwNTAsIm5iZiI6MTcwNzg1MDc1MCwicGF0aCI6Ii8yNDU0Njg0LzMwNDQwOTc3Ni1lMmQ3Y2JlMy1hNzI3LTQ0ZTEtYWM4Ni1mYjZkOGU3YTIwZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMTg1OTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDM0NjkxMTlmMGNhZjdiYmZjZGZkODVlN2YxMDYyZjY0N2ZmYTcyZDlmNmE0MzJlZTEzNWUzNTQ5NjAyZDU2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Na62bo2mU46oy0fYxrc2oxFmKUaMnVCZHP3jilvX-IE)

It seems the gap was due to missing sizes of different breakpoints (e.g. xs, sm, md, lg, xl, xxl). In the latest attempt, I still cannot find the best numbers to avoid the labels being broken into two lines while keeping the label not too wide. Maybe that's a compromise we have to make if we want the label width to scale with page width. (Let me know if the scaling behaviour was not intended / that the label being broken into two lines when displayed in an odd resolution is not acceptable. Then your suggestion to simply set a `min-width` and `width` is probably the best way to go with. )

2024-02-13 19:20 UTC, kirkrodrigues commented
> Maybe that's a compromise we have to make if we want the label width to scale with page width. (Let me know if the scaling behaviour was not intended / that the label being broken into two lines when displayed in an odd resolution is not acceptable. Then your suggestion to simply set a `min-width` and `width` is probably the best way to go with. )

Yeah, I'd prefer if the label width didn't scale (intuitively, I don't the user would expect it).

2024-02-14 05:45 UTC, junhaoliao commented
Kept the Bootstrap Grid system and only limited the container size :)
![image](https://github.com/y-scope/clp/assets/43196707/4fad0d39-8e83-4bc5-bf3f-a69ec01f38ba)
![image](https://github.com/y-scope/clp/assets/43196707/35f2da43-81f9-4a60-b285-c6a31abc1565)
![image](https://github.com/y-scope/clp/assets/43196707/fca7d5e4-0c29-47d8-9297-d0049c6b9586)
![image](https://github.com/y-scope/clp/assets/43196707/97496207-67a6-4ac5-b654-e88ff0b6fe48)

2024-02-14 10:32 UTC, kirkrodrigues requested changes
Sorry, not to beat a dead horse, but the spacing still seems a bit too wide:

![image](https://github.com/y-scope/clp/assets/2454684/434ff37f-30ff-48b0-993a-ae231850db95)

2024-02-14 12:02 UTC, junhaoliao commented on components/webui/imports/ui/SearchView/SearchControls.jsx
> +        llg={1}/>
I meant to configure `xxl`. 🤦

Still, in the latest commit I got it fixed by specifying a `min-width` on the label where we can keep the Grid system with the label text broken into two lines. 

![image](https://github.com/y-scope/clp/assets/43196707/17b19ad0-d89d-43e1-afe2-14878cb03972)

2024-02-14 12:06 UTC, junhaoliao commented on components/webui/imports/ui/SearchView/SearchControls.jsx
> +     * @returns {void}
Feel free to object - 

I think it's better to explicitly state the return type for every function, and we can rely on `valid-jsdoc` to catch the ones that are not supposed to return `void` but we do not have the `@returns` specified in the JSDoc.

2024-02-14 12:23 UTC, kirkrodrigues commented on components/webui/imports/ui/SearchView/SearchControls.jsx
> +     * @returns {void}
Does valid-jsdoc warn if we don't have `@returns {void}`?

2024-02-14 12:24 UTC, kirkrodrigues submitted a review, later dismissed
Commit msg: `webui: Add case-sensitivity search control; Fix incorrect debug log. (#280)`?

2024-02-14 12:43 UTC, kirkrodrigues commented on components/webui/imports/ui/SearchView/SearchControls.jsx
> +     * @returns {void}
Haven't tried it, but looking at the [docs](https://eslint.org/docs/latest/rules/valid-jsdoc#options), it looks like we can specify `requireReturn: false` to have `valid-jsdoc` only warn for methods that actually return something.

2024-02-14 12:46 UTC, junhaoliao commented on components/webui/imports/ui/SearchView/SearchControls.jsx
> +     * @returns {void}
Let me remove the `@returns` to keep the docs less verbose then.

2024-02-14 12:51 UTC, kirkrodrigues approved these changes

2024-02-14 12:53 UTC, merged