Remove interactive docker exec calls to allow use in unattended scripts.
y-scope/clp pull request #282
Opened 2024-02-13 18:44 UTC by haiqi96

# Description
Remove the "-it" from the docker command in the start CLP script because cloud-init doesn't support docker with interactive mode

# Validation performed
Ran the package locally and on the docker and verifed that the script waits for database and queue to start.

2024-02-13 23:06 UTC, kirkrodrigues requested changes

2024-02-15 02:36 UTC, haiqi96 commented on components/clp-package-utils/clp_package_utils/scripts/start_clp.py
> +    rabbitmq_cmd = ["rabbitmqctl", "status"]
You are right, the [rabbitmq-diagnostics check_running](https://www.rabbitmq.com/rabbitmq-diagnostics.8.html#check_running) seems to be what I should really use.

2024-02-15 04:15 UTC, kirkrodrigues requested changes

2024-02-15 04:15 UTC, kirkrodrigues commented on components/clp-package-utils/clp_package_utils/scripts/start_clp.py
> +    logger.error(f"Timeout while waiting for cmd {flatten_cmd} to run after {timeout} seconds")
```suggestion
    logger.error(f"Timeout while waiting for command '{cmd_str}' to run after {timeout} seconds")
```

2024-02-15 04:15 UTC, kirkrodrigues commented on components/clp-package-utils/clp_package_utils/scripts/start_clp.py
> +    logger.error(f"Timeout while waiting for cmd {flatten_cmd} to run after {timeout} seconds")
Missed from last review

2024-02-15 04:15 UTC, kirkrodrigues commented on components/clp-package-utils/clp_package_utils/scripts/start_clp.py
> +
```suggestion
```

2024-02-15 04:24 UTC, haiqi96 commented on components/clp-package-utils/clp_package_utils/scripts/start_clp.py
> +    logger.error(f"Timeout while waiting for cmd {flatten_cmd} to run after {timeout} seconds")
GG

2024-02-15 05:05 UTC, kirkrodrigues approved these changes
Commit msg: `Remove interactive docker exec calls to allow use in unattended scripts. (#282)`?

2024-02-15 05:53 UTC, merged