clp-package: Pass input paths to compression scheduler through database rather than file.
y-scope/clp pull request #307
Opened 2024-02-29 15:05 UTC by haiqi96

# Description

The current way of argument passing uses an on-disk file and doesn't handle the case when compress.sh is on a different machine from compression scheduler. This change replace the on-disk file with a list of file paths. 

# Validation performed

Manually ran compress.sh with file and input-list arguments and confirmed no error.

2024-02-29 15:41 UTC, haiqi96 commented
In fact, the compress.py only use --input-list to to pass argumets to native/compress.py.

If replacing postional argument PATH to be -p is not preferred, we can consider removing PATH from native/compress.py and make input-list to be a required argument

2024-02-29 20:14 UTC, kirkrodrigues requested changes

2024-02-29 20:14 UTC, kirkrodrigues commented on components/clp-package-utils/clp_package_utils/scripts/native/compress.py
> +    compression_paths = parsed_args.paths
Can we do some renaming:
* `--input-list` -> `--path-list`
* `compression_paths` -> `paths_arg` (or if you want to be more specific, `compress_paths_arg`)
* `compression_input_list` -> `path_list_arg` (or if you want to be more specific `compress_path_list_arg`)
* `list_path` -> `paths_to_compress`
* `InputConfig.list_path` -> `InputConfig.paths_to_compress`

2024-02-29 21:39 UTC, kirkrodrigues requested changes

2024-02-29 21:39 UTC, kirkrodrigues commented on components/clp-package-utils/clp_package_utils/scripts/native/compress.py
> +        log_paths_to_compress = pathlib.Path(compress_path_list_arg).resolve()
`compress_path_list_path`? `log_paths_to_compress` sounds like a list but in this case it's a file path to a list of log paths.

2024-02-29 21:39 UTC, kirkrodrigues commented on components/clp-package-utils/clp_package_utils/scripts/compress.py
> +            container_path_list = clp_config.logs_directory / container_path_list_filename
`container_path_list_path`?

2024-03-01 01:41 UTC, kirkrodrigues approved these changes
How about this?

clp-package: Pass input paths to compression scheduler through database rather than file. (#307)

2024-03-01 03:40 UTC, merged