Limit number of results in subscription `results` by `SEARCH_MAX_NUM_RESULTS`.
y-scope/clp pull request #311
Opened 2024-03-03 20:49 UTC by junhaoliao

# References
The number of search results in MongoDB might be higher than request argument `max_num_results` due to concurrency between workers, but we still want to restrict the view to the latest `max_num_results` of results and handle sorting. 

# Description
1. Limit number of results in subscription `results` by `SEARCH_MAX_NUM_RESULTS`.
   1. In the `results` subscription handler, instead of setting MongoDB collection find options `limit=visibleSearchResultsLimit` and `sort={...fieldToSortBy}`, always set `limit=SEARCH_MAX_NUM_RESULTS=1000` and `sort=[["timestamp", "desc"]]` so that the subscription always provide the latest `SEARCH_MAX_NUM_RESULTS=1000` results to its subscribers.
   2. In the `results` subscriber, set MongoDB collection find options `limit=visibleSearchResultsLimit` and `sort={...fieldToSortBy}` to manipulate the results returned by the `results` subscription handler.
2. Correct results table sort icon directions:
   `▲`: "ascending", as the triangle tip points upwards.
   `▼`: "descending", as the triangle tip points downwards.

# Validation performed
1. Built and started `clp-package`. Compressed sample logs.
2. Open the WebUI address http://localhost:4000 in a browser.
3. Started a search query with string `1` and time range "All Time". 
4. Observed the initial results to be sorted in timestamp descending order.
5. Toggled the table `timestamp` header sort button and observed the button shows the logs are not sorted by timestamp. Observed no change in the logs order as the default is to sorting the logs by descending timestamp when users do not provide a sort condition. 
6. Toggled the `timestamp` header sort button and observed the button shows the logs are sorted by ascending timestamp. Kept scrolling down to load more results and observed the logs to be presented in ascending timestamp order.

To ensure the latest `SEARCH_MAX_NUM_RESULTS` are returned:
1. `./stop-clp.sh webui` and launch WebUI in debug mode as specified by `<PROJECT_ROOT>/components/webui/README.md`.
2. Modified `SEARCH_MAX_NUM_RESULTS` from `1000` to `3`.
3. Started a search query with string `1` and time range "All Time". 
4. Observed the latest 3 results to be presented in the results table. 
5. Toggled the `timestamp` header sort button twice to sort in "ascending" timestamp mode. Observed the 3 logs' timestamp and content do not change, except their listing order.

2024-03-04 20:27 UTC, kirkrodrigues requested changes
Nice work. Some minor comments.

2024-03-04 20:27 UTC, kirkrodrigues commented on components/webui/imports/api/search/server/methods.js
> +    const countedNumTotalResults = await searchJobCollectionsManager
How about `numResultsInCollection`?

2024-03-04 23:36 UTC, junhaoliao commented on components/webui/imports/api/search/server/publications.js
> +            ["timestamp", "desc"],
Right, the `_id` subsort was moved to the frontend to prevent the situation you mentioned, but I missed that the backend also needs the subsort.

2024-03-05 04:50 UTC, kirkrodrigues requested changes

2024-03-05 04:50 UTC, kirkrodrigues commented on components/webui/imports/ui/SearchView/SearchView.jsx
>                  // The check prevents clearing `localLastSearchSignal = SearchSignal.REQ_QUERYING`
```suggestion
                // The check prevents clearing `localLastSearchSignal = SEARCH_SIGNAL.REQ_QUERYING`
```

2024-03-05 04:50 UTC, kirkrodrigues commented on components/webui/imports/ui/SearchView/SearchResultsTable.jsx
> +                        <FontAwesomeIcon icon={getSortIcon(fieldToSortBy, SEARCH_RESULTS_FIELDS.TIMESTAMP)}/> Timestamp
Wrap to within 100 chars.

2024-03-05 04:50 UTC, kirkrodrigues commented on components/webui/imports/ui/SearchView/SearchView.jsx
> +                    "_id",
```suggestion
                    SEARCH_RESULTS_FIELDS.ID,
```

2024-03-05 05:04 UTC, kirkrodrigues approved these changes
How about:

webui: Fetch and display up to `SEARCH_MAX_NUM_RESULTS` search results. (#311)

2024-03-05 16:13 UTC, merged