clp-package: Add support for time bucketed count aggregations.
y-scope/clp pull request #331
Opened 2024-03-22 15:25 UTC by gibber9809

# Description
This PR adds support for performing count aggregations grouped by time buckets. From the command line users can provide the `--time-bucket-size <ms>`  alongside the `--count` option to `/sbin/search.sh` to trigger timeline count aggregations.

This feature will be used to support a result timeline view in the webui.

# Validation performed
- Validated that time bucketed count aggregation works correctly with clp and clp-s

2024-03-23 09:28 UTC, kirkrodrigues requested changes
As discussed offline, let's rename `time-bucket-size` to `count-by-time` where appropriate. Added some inline comments as well.

2024-03-23 09:28 UTC, kirkrodrigues commented on components/core/src/clp_s/search/OutputHandler.cpp
> +                        "count"
Can we deduplicate this magic string in the reducer?

2024-03-25 14:56 UTC, gibber9809 commented on components/core/src/clp_s/search/OutputHandler.cpp
> +        SPDLOG_ERROR("Failed to send results to reducer");
I think I should probably refactor the flush methods for all of the output handlers then -- some of them are using exception throwing to report errors. Do you think it's best to have everything throw errors, return specific error codes, or just return a bool failure/success? I generally prefer code that doesn't throw, so leaning towards the second or third option.

2024-03-25 15:22 UTC, kirkrodrigues commented on components/core/src/clp_s/search/OutputHandler.cpp
> +        SPDLOG_ERROR("Failed to send results to reducer");
Code makes sense to me.

2024-03-26 00:21 UTC, kirkrodrigues requested changes
Small fixes

2024-03-26 00:21 UTC, kirkrodrigues commented on components/clp-package-utils/clp_package_utils/scripts/native/search.py
> +        help="Perform the query and count the number of results in each time bucket (ms).",
```suggestion
        help="Count the number of results in each time span of the given size (ms).",
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/clp-package-utils/clp_package_utils/scripts/native/search.py
>          help="Perform the query and count the number of results.",
```suggestion
        help="Count the number of results.",
```
Sorry, I think you had something like this the previous PR and I thought it was unclear. But in light of the new option, I think it's simpler.

2024-03-26 00:21 UTC, kirkrodrigues commented on components/clp-package-utils/clp_package_utils/scripts/search.py
>          "--count", action="store_true", help="Perform the query and count the number of results."
Ditto

2024-03-26 00:21 UTC, kirkrodrigues commented on components/clp-package-utils/clp_package_utils/scripts/search.py
> +        help="Perform the query and count the number of results in each time bucket (ms).",
Ditto

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/clo.cpp
> +                "Encoutered error '{}' while trying to flush output handler.",
```suggestion
                "Failed to flush output handler, error={}",
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/CommandLineArguments.cpp
> +            "Perform the query and count the number of results in each time bucket (ms)"
Ditto

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/CommandLineArguments.cpp
> +            po::value<int64_t>(&m_count_by_time_bucket_size),
```suggestion
            po::value<int64_t>(&m_count_by_time_bucket_size)->value_name("SIZE"),
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/CommandLineArguments.cpp
>              "Perform a count aggregation (count the number of results)"
Ditto

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/CommandLineArguments.cpp
> +        if (parsed_command_line_options.count("count-by-time")) {
```suggestion
        if (parsed_command_line_options.count("count-by-time") > 0) {
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/CommandLineArguments.cpp
> +                throw std::invalid_argument("Count by time argument must be greater than zero.");
```suggestion
                throw std::invalid_argument("Value for count-by-time must be greater than zero.");
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/CommandLineArguments.cpp
> +        bool aggregtion_was_specified
Typo

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/CommandLineArguments.cpp
> +                    "The --count-by-time and --count arguments are mutually exclusive."
```suggestion
                    "The --count-by-time and --count options are mutually exclusive."
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/OutputHandler.hpp
> +    ErrorCode flush() override {
```suggestion
    /**
     * Closes the connection.
     * @return ErrorCode_Success
     */
    ErrorCode flush() override {
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/OutputHandler.hpp
> +    ErrorCode flush() override {
Reason being, the base method doesn't document the specific return values.

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/OutputHandler.hpp
> +    ErrorCode flush() override;
```suggestion
    /**
     * Flushes any buffered output.
     * @return ErrorCode_Success on success
     * @return ErrorCode_Failure_DB_Bulk_Write on failure to write results to the results cache
     */
    ErrorCode flush() override;
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/OutputHandler.hpp
> +    ErrorCode flush() override;
```suggestion
    /**
     * Flushes the counts.
     * @return ErrorCode_Success on success
     * @return ErrorCode_Failure_Network on network error
     */
    ErrorCode flush() override;
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/OutputHandler.hpp
> +    ErrorCode flush() override;
```suggestion
    /**
     * Flushes the count.
     * @return ErrorCode_Success on success
     * @return ErrorCode_Failure_Network on network error
     */
    ErrorCode flush() override;
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/search/Output.cpp
> +                    "Encoutered error '{}' while trying to flush output handler.",
```suggestion
                    "Failed to flush output handler, error={}.",
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/search/Output.cpp
> +                "Encoutered error '{}' while trying to finish output handler.",
```suggestion
                "Failed to flush output handler, error={}.",
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/search/Output.hpp
> +     * @return whether the filter was performed succesfully
```suggestion
     * @return Whether the filter was performed successfully
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/search/OutputHandler.hpp
> +    ErrorCode flush() override;
```suggestion
    /**
     * Flushes the output handler after each table that gets searched.
     * @return ErrorCodeSuccess on success
     * @return ErrorCodeFailureDbBulkWrite on failure to write results to the results cache
     */
    ErrorCode flush() override;
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/search/OutputHandler.hpp
> +    ErrorCode finish() override;
```suggestion
    /**
     * Flushes the count.
     * @return ErrorCodeSuccess on success
     * @return ErrorCodeFailureNetwork on network error
     */
    ErrorCode finish() override;
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/search/OutputHandler.hpp
> +    ErrorCode finish() override;
```suggestion
    /**
     * Flushes the counts.
     * @return ErrorCodeSuccess on success
     * @return ErrorCodeFailureNetwork on network error
     */
    ErrorCode finish() override;
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/CommandLineArguments.cpp
>                      "Perform a count aggregation (count the number of results)"
Ditto

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/CommandLineArguments.cpp
> +                    po::value<int64_t>(&m_count_by_time_bucket_size),
```suggestion
                    po::value<int64_t>(&m_count_by_time_bucket_size)->value_name("SIZE"),
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/CommandLineArguments.cpp
> +                    "Perform the query and count the number of results in each time bucket (ms)"
Ditto

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/CommandLineArguments.cpp
> +            if (parsed_command_line_options.count("count-by-time")) {
```suggestion
            if (parsed_command_line_options.count("count-by-time") > 0) {
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/CommandLineArguments.cpp
> +                    throw std::invalid_argument("Bucket size argument must be greater than zero.");
```suggestion
                    throw std::invalid_argument("Value for count-by-time must be greater than zero."
                    );
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/CommandLineArguments.cpp
> +            bool aggregtion_was_specified
Typo

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/CommandLineArguments.cpp
> +                        "The --count-by-time and --count arguments are mutually exclusive."
```suggestion
                        "The --count-by-time and --count options are mutually exclusive."
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/job-orchestration/job_orchestration/scheduler/job_config.py
> +    count_by_time_bucket_size: typing.Optional[int] = None
```suggestion
    count_by_time_bucket_size: typing.Optional[int] = None  // Milliseconds
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/job-orchestration/job_orchestration/scheduler/search/reducer_handler.py
> +                            "count_by_time_bucket_size": aggregation_config.count_by_time_bucket_size,
Let's extract this into a var so that it doesn't violate the line length

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp/clo/CommandLineArguments.hpp
> +    int64_t m_count_by_time_bucket_size{0};
```suggestion
    int64_t m_count_by_time_bucket_size{0};  // Milliseconds
```

2024-03-26 00:21 UTC, kirkrodrigues commented on components/core/src/clp_s/CommandLineArguments.hpp
> +    int64_t m_count_by_time_bucket_size{0};
```suggestion
    int64_t m_count_by_time_bucket_size{0};  // Milliseconds
```

2024-03-26 11:18 UTC, kirkrodrigues commented on components/job-orchestration/job_orchestration/scheduler/job_config.py
> +    count_by_time_bucket_size: typing.Optional[int] = None
Sorry, I used the wrong comment format here.

2024-03-26 18:44 UTC, kirkrodrigues approved these changes
Updated the commit message slightly.

2024-03-26 19:10 UTC, merged