webui: Fix a bug where collapsing the sidebar clears the search results.
y-scope/clp pull request #336
Opened 2024-03-26 22:02 UTC by junhaoliao

# References
Internally it was found that collapsing / expanding the sidebar would clear the search results. Further investigation found that the search page was re-rendered when the `isSidebarCollapsed` state variable got updated, causing unnecessary and undesired re-render of page contents. 

# Description
1. Change `Route` from a function component into a variable to avoid regeneration of the route switch.
 
# Validation performed
1. `cd <PROJECT_ROOT>; task`
2. `cd ./build/clp-package/sbin; ./start-clp.sh`
3. `./compress.sh ~/samples/hive-24hr/i-00c90a0f/`
4. Opened the WebUI address in a browser.
5. Started a query with string `123` and observed the job finished and the results are displayed in the results table.
6. Clicked the "Collapse" button to collapse the sidebar and observed the results still present within the search page.
7. Clicked the "Expand" button to expand the sidebar and observed the results still present within the search page.

2024-03-26 22:14 UTC, junhaoliao commented
Please put this review on hold. Let me also remove the unused user authentication system in this PR instead.

2024-03-26 22:29 UTC, junhaoliao commented
The PR descriptions have been updated. Please resume the review.

2024-03-27 17:37 UTC, kirkrodrigues requested changes

2024-03-27 17:37 UTC, kirkrodrigues commented on components/webui/imports/ui/App.jsx
> -    const [loggedIn, setLoggedIn] = React.useState(false);
Also remove calls to `login` and `setLoggedIn`

2024-03-27 18:56 UTC, kirkrodrigues approved these changes
How about:

webui: Don't use an expression to render routes to avoid unnecessary re-renders. (#336)

(At least that's my understanding of the issue.)

2024-03-27 19:24 UTC, junhaoliao commented
> How about:
> 
> webui: Don't use an expression to render routes to avoid unnecessary re-renders. (#336)
> 
> (At least that's my understanding of the issue.)

JSX itself is an expression, but sometimes React is smart enough to avoid re-evaluation of the JSX. The [initial fix](https://github.com/y-scope/clp/pull/336/commits/864f5111816d645ba5b6ae673ea7cdf623904833) does exactly that although the `routeSwtich` constant was later inlined. Supposedly another fix is to keep the `<Routes/>` as a component and move it out of the `<App/>`.

It might be more clear to say `webui: Avoid unnecessary React route-switch re-render within functional components. (#336)`. What do you think?

2024-03-27 19:36 UTC, merged