webui: Update job status when the job is cancelled; parallelize meteor method handlers; Change `SEARCH_SIGNAL` enums to strings instead of numbers.
y-scope/clp pull request #337
Opened 2024-03-26 22:03 UTC by junhaoliao

# References
Internally, it was discovered that:
1. When the job is cancelled by the user, the progress bar is still running. 
2. There are delays in UI updates after a search job is submitted.
3. It is hard to debug a job's `lastSignal`, which is a aggregated state from <u>the last request by user</u> and <u>the last response by server </u>, because the field appears as an base-10 integer in the MongoDB. Decimal to hex conversion is usually needed before developers can infer the status code. 

# Description
1. Update job status when the job is cancelled.
2. Parallelize meteor method handlers.
3. Change `SEARCH_SIGNAL` enums to strings instead of numbers.

# Validation performed
1. `cd <PROJECT_ROOT>; task`
2. `cd ./build/clp-package/sbin; ./start-clp.sh`
3. `./compress.sh ~/samples/hive-24hr/i-00c90a0f/`
4. Opened the WebUI address in a browser.
5. Started a query with string `123` and observed the job finished and the results are displayed in the results table.
6. Started another query with string `1234` and cancelled the job before the job finished. Observed the progress bar to disappear and an error message is displayed as "The search results are inconclusive because the user cancelled the job.". 
   ![image](https://github.com/y-scope/clp/assets/43196707/e3d2ee11-3bec-4057-ab83-cb55d8927fec)
7. Checked the `results-metadata` in MongoDB using MongoDB Compass and verified the job's last signal is a string of `resp-done` than an integer.

2024-04-03 22:34 UTC, kirkrodrigues requested changes
As discussed offline, let's make sure we need `this.unblock()` since the code is easier to reason about if we don't use it.

2024-04-03 22:34 UTC, kirkrodrigues commented on components/webui/imports/api/search/server/methods.js
> +        _id: jobId.toString(),
To mitigate races, perhaps we should also take in and use the expected previous state in the filter?

2024-04-05 08:33 UTC, junhaoliao commented
> As discussed offline, let's make sure we need `this.unblock()` since the code is easier to reason about if we don't use it.

To address the discussed concerns, I performed some tests in a CPU-stressed environment (`stress -cpu 24`). According to the WebSocket Send/Receive messages timestamps, it is confirmed that adding `this.unblock()` does accelerate the time to get a response from the method `search.submitQuery` (`jobId`).

1. First trial:
   ![a28e71a5d827284b8584f40a9c4cfe7](https://github.com/y-scope/clp/assets/43196707/a0a6c41b-d9c4-418a-818c-1aeda344852b)
2. Second trial:
   ![dd37e7bafde3746431d0e7a8a9d0e37](https://github.com/y-scope/clp/assets/43196707/6be774d0-d702-4f89-8837-b9b218937d91)
3. Third trial:
   ![c2e31a9b0024bbb092209bc99e23a0d](https://github.com/y-scope/clp/assets/43196707/9942c828-8265-4d7c-b567-c462c34d3953)

| Trial | with `this.unblock()` | w/o`this.unblock()` | Speed up |
|-------|-----------------------|---------------------|----------|
| 1     | 59                    | 953                 |          |
| 2     | 47                    | 490                 |          |
| 3     | 91                    | 797                 |          |
| SUM   | 197                   | 2240                | 11.37056 |

2024-04-08 17:10 UTC, kirkrodrigues approved these changes
How about:

webui: Improve cancellation behaviour: (#337)

- Update job status when job is cancelled
- Parallelize Meteor method handlers
- Change `SEARCH_SIGNAL` enum values from numbers to strings

2024-04-08 17:52 UTC, merged