webui: Replace mysql2 connection with connection pool.
y-scope/clp pull request #338
Opened 2024-03-27 06:35 UTC by junhaoliao

# References
Internally, it was found that any clp-package instances running beyond some intermittent time would face connection error issues in the WebUI. The issue is believed to be related to the [`wait_timeout`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout) setting, which has a default of `28800 seconds = 8 hours`. By setting it to an even shorter interval of `2 seconds`, the issue was reproduced and the cause was confirmed.

Through a series of experiments and in-depth analysis, several strategies have been identified that may provide a solution to the observed `wait_timeout` problem.

1. **Ineffectiveness of the mysql2 `enableKeepAlive` option**
   It has been observed that enabling the `enableKeepAlive` option in `mysql2` connections does not mitigate the `wait_timeout` issue. Contrary to suggestions in various online discussions, setting `enableKeepAlive` to true, which is the default behavior, merely adjusts TCP socket options managed by Node.js without effectively maintaining the MySQL connection active. These options include:
    - `SO_KEEPALIVE=1`
    - `TCP_KEEPIDLE=initialDelay`
    - `TCP_KEEPCNT=10`
    - `TCP_KEEPINTVL=1`

   (Despite these settings, analysis with tools such as Wireshark revealed no significant keep-alive packet transmission to port 3306.) Further examination of the MariaDB source code indicates that `wait_timeout` serves as a read timeouts, rendering keep-alive packets ineffective due to their lack of actual data payload.

2. **Modifying the compression stats polling handler:**

   Running `show processlist;` reveals three connections (excluding the querying and WebUI connections) that typically display a "Sleep" command, indicating idle status. These are polling connections from schedulers. 

   The WebUI also queries compression stats every 5 seconds. However, this query is skipped if no active connection is detected ([source code](https://github.com/y-scope/clp/blob/d6cf6e492863ec1de85da316c6d72742bea28329/components/webui/imports/api/ingestion/server/publications.js#L29)). By commenting out these checks, the idle time remains significantly lower than the default `wait_timeout` of 8 hours.

3. **Interval-based connection pinging:**

   Setting up an interval to periodically execute `connection.ping()` offers an efficient way to maintain connection vitality. `PING` packets are preferable to `STMT_EXECUTE` packets due to their lower overhead.

4. **Utilizing a Connection Pool:**

   As previously discussed, employing a connection pool can address connection management issues. The mysql2 documentation advises releasing connections back to the pool after use, which require some significant changes in the DB Managers arch. In fact, there is also a not well-documented `pool.execute()` metho,d where we can treat pool handles as connection handles. 
   Instead of adhering to the default connectionLimit of 10, we can adjust it to 2 (one for stats polling and up to two for searching, when polling job status and processing user cancellation requests). Also, given the stats polling interval of 5 seconds, the idleTimeout can be reduced to 10,000 milliseconds, compared to the default 60,000 milliseconds.

# Description
1. Implement Option 4 as discussed above. 

# Validation performed
1. `cd <PROJECT_ROOT>; task`
2. `cd ./build/clp-package/`
3. Modify MariaDB options: `printf "[mysqld]\nwait_timeout=2\n" > ./etc/mysql/conf.d/wait_timeout.cnf`
4. `./sbin/start-clp.sh`
5. `./sbin/compress.sh ~/samples/hive-24hr/i-00c90a0f/`
6. Opened the WebUI address in a browser.
7. `./sbin/compress.sh ~/samples/hive-24hr/i-1ec90a11/` and observed the compression stats to be updated in 5 seconds after the compression job finished.

2024-03-27 18:29 UTC, junhaoliao commented
Offline @jackluo923 proposed we can also look into internal / external DB proxies for connections pooling, which helps reducing connections to the central DB in a distributed cloud setting.

2024-03-27 19:40 UTC, haiqi96 commented
As discussed previously, what would happen to the pool if the database itself is down and back online after a while. would the pool be able to reconnect to the database?

2024-03-27 21:41 UTC, junhaoliao commented
> As discussed previously, what would happen to the pool if the database itself is down and back online after a while. would the pool be able to reconnect to the database?

That right but there could be one edge case. Whenever the TCP connection is ended:
1. By the sql server actively sending out a `FIN`, the Node.js TCP socket will receive an `end` event, which is then [propagated](https://github.com/sidorares/node-mysql2/blob/a9c6c3eab0691ee03482514080d70d90344d0326/lib/connection.js#L106C1-L109C8) to the Pool's `end` [event handler to remove the connection from the pool](https://github.com/sidorares/node-mysql2/blob/a9c6c3eab0691ee03482514080d70d90344d0326/lib/pool_connection.js#L15-L17).
2. Abruptly without sending out a `FIN` packet. Note that we do enable "keepAlive" on the Node.js TCP socket by default, which helps the client side to find the server is dead. As listed out by Option 1, when `keepAlive` is enabled, staring from `TCP_KEEPIDLE=initialDelay=0` second of the connection establishment, every `TCP_KEEPINTVL=1` second the client sends out one probe to the server. If after `(TCP_KEEPCNT=10) / (TCP_KEEPINTVL=1) = 10` seconds the server does not send out a response to the probes back to the client, the client would consider the connection dead and the Node.js TCP socket would emit an "error" event followed by an "end" event, both of which are handled and the connection will be removed from the pool. [(Note the connections' `connectTimeout` default is also 10 seconds.)](https://sidorares.github.io/node-mysql2/docs/examples/connections/create-pool)
   There is one caveat though - I don't see any retrying logics in lib `mysql2` if send error happens when socket is consider connected (in the initial 10 seconds the SQL server's OS platform crashes / gateway or firewall drops the connection without sending `FIN`/`RST` / the SQL server's OS platform 's network interface is down). This scenario is only encountered when the client establishes a connection -> the connection becomes dead without `FIN`/`RST` -> the client connection finds out the server is dead after 10 seconds -> the `mysql2` lib finds an error in the Node.js socket and just throws it. For the connection to poll compression stats every 5 seconds, at least a single attempt would fail (in max 10s, before that another query should have been started); for a user action to start / stop queries, the action would fail and users would see the error message and restart the action. Such dead connections are catastrophic and not expected to happen frequently.

2024-03-28 01:51 UTC, haiqi96 approved these changes
Thanks for the detail explanation. Then I think it should be fine since I would expect we warn user not to use their deployment before we run any database update.

In that case, the only connection to the database would be the connection polling which shouldn't run into the corner case

2024-03-28 02:57 UTC, kirkrodrigues requested changes
Small name change request

2024-03-28 02:57 UTC, kirkrodrigues commented on components/webui/imports/api/ingestion/server/StatsDbManager.js
> +    #sqlDbPool;
How about `sqlDbConnPool`?

2024-03-30 00:41 UTC, kirkrodrigues approved these changes
How about:

webui: Replace MySQL connection with connection pool. (#338)

2024-03-30 03:29 UTC, merged