clp: Add maximum length for utf8 validation (fixes #242).
y-scope/clp pull request #347
Opened 2024-04-03 21:21 UTC by haiqi96

# References
https://github.com/y-scope/clp/issues/242

# Description
The issue identified in https://github.com/y-scope/clp/issues/242 is not a real issue. It was caused by a size change in the validation buffer. so a non-utf8 char that was not detected by the previous 4k buffer size is revealed by 64k buffer. The decision is to let CLP only read the first 4096 bytes of a file for utf8 validation.

# Validation performed
Compressed the var-logs and verified that the error observed in issue 242 is gone.

2024-04-04 07:25 UTC, LinZhihao-723 commented on components/core/src/clp/clp/FileCompressor.hpp
> +    size_t const m_utf_max_validation_len = 4096;
Maybe use `constexpr`?

2024-04-05 01:43 UTC, LinZhihao-723 commented on components/core/src/clp/clp/FileCompressor.hpp
> +    static constexpr size_t m_utf_max_validation_len = 4;
```suggestion
    static constexpr size_t cUtfMaxValidationLen = 4;
```
naming convention for constexpr data members

2024-04-05 02:02 UTC, kirkrodrigues requested changes
Small changes

2024-04-05 02:02 UTC, kirkrodrigues commented on components/core/src/clp/clp/FileCompressor.cpp
> +    size_t utf8_validation_buf_len = std::min(peek_size, m_utf_max_validation_len);
```suggestion
    auto utf8_validation_buf_len = std::min(peek_size, m_utf_max_validation_len);
```

2024-04-05 02:02 UTC, kirkrodrigues commented on components/core/src/clp/clp/FileCompressor.cpp
> +        size_t utf8_validation_buf_len = std::min(peek_size, m_utf_max_validation_len);
```suggestion
        auto utf8_validation_buf_len = std::min(peek_size, m_utf_max_validation_len);
```

2024-04-05 02:09 UTC, haiqi96 commented on components/core/src/clp/clp/FileCompressor.hpp
> -
GG, must have caused by very slow clion when I made the 2nd fix

2024-04-05 02:12 UTC, kirkrodrigues approved these changes

2024-04-05 02:13 UTC, LinZhihao-723 approved these changes
lgtm

2024-04-05 02:47 UTC, merged