core: Add unit test to cover basic SQLite Database functionalities.
y-scope/clp pull request #380
Opened 2024-05-02 18:07 UTC by LinZhihao-723

# References

# Description

Before this PR, we don't have unit test coverage for SQLite Database functionalities. This PR implements a simple SQLite DB unit test, which includes the following testing flow:
1. The test case will create a new database with a fixed testing table schema.
2. Insert data rows into the database.
3. Persist the database to the disk.
4. Open the created database and create indices.
5. Iterate data rows from the database with a certain ordering (with select statement).
6. Ensure the read results are the same as the input data in step 2, with the expected ordering.
Notice that this PR only provides a skeleton for SQLite functionality testing. It doesn't cover all the SQLite db usage we have in the current `clp` implementation. We will add more tests later when we push new SQLite abstracted features, such as `SQLitePreparedSelectStatement`.

# Validation performed

1. Passed `clang-tidy` linting check.
2. Ensure unit tests are passed locally in Linux.
3. GH Workflow on-going.

2024-05-03 23:13 UTC, kirkrodrigues requested changes

2024-05-03 23:13 UTC, kirkrodrigues commented on components/core/tests/test-SQLiteDB.cpp
I think we can make the correspondence between the prepared statements and the IDs that we use to bind values and retrieve values more clear (and less misleading for future devs who read this code as a way to learn how to use SQLiteDB).

Since IDs of template parameters in a SQLite prepared statement are arbitrary, I think we should write the logic so that the IDs we use in the template *don't* correspond to the order that we create columns in the table. For instance, we could create the prepared statement `INSERT INTO table (col2, col3, col1) VALUES (?1, ?1, ?2)`. Notice that we aren't specifying the columns in order and we have template parameter that appears twice. Then when binding values to the parameters, we have to ensure the code matches the template parameter's ID to the value we actually want to bind (which definitely doesn't match the order nor the number of columns in the table).

Similarly, since the orders of columns in a SQLite SELECT statement is arbitrary, I think we should write the logic so that the columns we select from the template *don't* correspond to the order nor the number of columns that we create in the table. For instance, we could create the prepared statement `SELECT col3, col1 FROM table ORDER BY col1`. Notice that we're not selecting all columns and the columns we do select are not in the order that we added them to the table.

By doing this, I think it'll also be clear that we want to keep the definition of the statement close to where we use the statement so that, in the case of a select statement, we can ensure the order and number of column values we retrieve corresponds to the statement; similarly, for a statement with template parameters, we want the definition to be close to where we bind values to it so that we can ensure we're binding the relevant values to the parameters. 

As the current code is written, we're creating the insert statement in one method (`sqlite_db_create`) and depending on the order of columns in the table schema; then we're binding the values to that statement in a far away method (`Row::insert_to_table`). We do still depend on the order of columns in the table schema, but that easily breaks down if we don't want to insert values in the exact order that we added columns to the table.

In the current code, it's good that the select statement is defined close to where we retrieve values from it. The only issue is we're still depending on the order that we added columns to the table.

I think by rewriting the code as suggested, it will also be clear where we can introduce some utility classes to make this whole process easier. I should say that it's tempting to introduce classes in this unit test to make things easier, but at that point, we're implementing the classes we actually want to use outside the tests; so I think it's important to keep things clear and simple.

2024-05-04 03:13 UTC, LinZhihao-723 commented on components/core/tests/test-SQLiteDB.cpp
> + * Gets the test table schema which has a global storage. It will be initialized only once.
This ensures we only need to create the table schema once (and can be used across multiple test cases).

2024-05-04 03:14 UTC, LinZhihao-723 commented on components/core/tests/test-SQLiteDB.cpp
> +    auto stmt_buf_ix{std::back_inserter(statement_buffer)};
sure

2024-05-05 00:36 UTC, kirkrodrigues commented on components/core/tests/test-SQLiteDB.cpp
> + * Gets the test table schema which has a global storage. It will be initialized only once.
Seems like a premature optimization, no? Generally, introducing global variables adds complexity to the code. It's also not clear to me that you couldn't create it once and pass it in to the methods that need it.

2024-05-13 05:43 UTC, kirkrodrigues requested changes

2024-05-13 05:43 UTC, kirkrodrigues commented on components/core/src/clp/SQLiteDB.cpp
> +        SPDLOG_WARN("Memory leak due to failure of closing sqlite database.");
```suggestion
        SPDLOG_WARN("Failed to close underlying SQLite database - this may cause a memory leak.");
```

2024-05-13 06:21 UTC, kirkrodrigues approved these changes
How about:

core: Add unit test to cover basic SQLite functionalities. (#380 )

2024-05-13 06:26 UTC, LinZhihao-723 commented
> How about:
> 
> core: Add unit test to cover basic SQLite functionalities. (#380 )

lgtm

2024-05-13 14:38 UTC, merged