clp-core: Add a field to track the message offset of file splits in CLP.
y-scope/clp pull request #412
Opened 2024-05-22 19:54 UTC by haiqi96

# References

# Description
CLP splits input file when the file size is greater than a threshold. Before this change, there is no simple way to know the range of log events index in each file split. The information can be inferred by ordering the file split in the ascending creation order and summing up the num_messages in each file split, which is inefficient and complicated.

This change adds a combined_file_msg_offset to both Archive and Global metadata database, so the value can be looked up easily from the database.

# Validation performed
Compressed and decompressed test input with CLP and CLP-S, ensured there is no error.
Manually examined the begin message offset in the database and confirmed their values are expected.

2024-05-24 18:10 UTC, kirkrodrigues commented on components/core/src/clp/streaming_archive/writer/File.hpp
> +     * Gets combined file message offset
I think we can omit the `Gets` description for pure getters and just use `@return`, even when it's inconsistent with the rest of the file. The idea being that we don't want to create extra work for ourselves in refactoring the file (and comments are low-impact places to be inconsistent). We could submit a PR right after this to make the docstrings consistent in this file.

2024-05-24 23:25 UTC, kirkrodrigues requested changes

2024-05-24 23:25 UTC, kirkrodrigues commented on components/clp-py-utils/clp_py_utils/initialize-clp-metadata-db.py
> +                    `begin_msg_idx` BIGINT NOT NULL,
This doesn't affect functionality, but it's nicer to be consistent about the ordering of columns here and in the other code---i.e., put `begin_message_ix` before `num_messages`.

2024-05-24 23:25 UTC, kirkrodrigues commented on components/core/src/clp/streaming_archive/Constants.hpp
> +constexpr char BeginMsgIdx[] = "begin_msg_idx";
Ditto

2024-05-24 23:25 UTC, kirkrodrigues commented on components/core/tools/scripts/db/init-db.py
> +                `begin_msg_idx` BIGINT NOT NULL,
Ditto

2024-05-24 23:25 UTC, kirkrodrigues commented on components/core/src/clp/streaming_archive/reader/File.cpp
> +    m_begin_msg_idx = file_metadata_ix.get_begin_msg_idx();
I would move this above just above where `m_num_messages` is set.

2024-05-24 23:25 UTC, kirkrodrigues commented on components/core/src/clp/streaming_archive/writer/File.hpp
> +     * @param offset
```suggestion
     * @param msg_idx
```

2024-05-24 23:25 UTC, kirkrodrigues commented on components/core/src/clp/streaming_archive/writer/Archive.hpp
> +     * @param file File to set the combined-file message msg_idx for
```suggestion
     * @param file
```

2024-05-24 23:25 UTC, kirkrodrigues commented on components/core/src/clp/streaming_archive/writer/utils.cpp
> +    auto const end_msg_idx = encoded_file.get_end_msg_idx();
If we're making the variables in `split_file` `const`, let's do the same here for consistency.

2024-05-27 17:16 UTC, LinZhihao-723 commented on components/core/src/clp/streaming_archive/writer/utils.cpp
> +    archive_writer.set_file_begin_message_ix(end_message_ix);
I think the begin message index should be passed in whenever a file is created and we should set it after creation. Let's make it as a parameter in `create_and_open_file`

2024-05-27 18:30 UTC, kirkrodrigues approved these changes
How about:

core: Add field to track index of first message in each file split. (#412)

2024-05-27 18:55 UTC, LinZhihao-723 approved these changes

2024-05-27 18:55 UTC, merged