ffi: Add support for IR serializer of the next IR stream format.
y-scope/clp pull request #446
Opened 2024-06-17 04:28 UTC by LinZhihao-723

# Description

When migrating to the next IR stream format, there are two important differences:
1. The serialization is no longer stateless in the next IR format. The stream has to maintain a schema tree across the entire IR stream.
2. In the current IR format, bytes can be written into the IR buffer in the same order as encoded: first encoded variables, then logtype, and finally timestamp. This is not true in the next IR format. For structured key-value pairs, the overall packet of a new record would be: [new_schema_tree_nodes, keys, values]. Each sub-packet has to be encoded in a separate buffer and merged into one after the entire record is processed. This means we need more than one internal buffer during the serialization, even though only the final merged buffer is exposed to the upper layer APIs.

To adapt to these changes, we wrap all the necessary data structures into a new class named `Serializer` to keep track of the states, as well as maintain necessary data structures. In details:
- It maintains an underlying schema tree for the stream.
- It maintains all the necessary internal buffers for serialization. These internal buffers are private members. In the future PRs, serialization methods will be added as member functions and they will have direct access to these buffers.
- It provides an API to access the view of the serialized IR buffer (containing serialized bytes).

Note: this class is designed to provide serialization functionalities only. The upper-level caller should be responsible for writing the serialized bytes into IO streams properly. In addition, it doesn't provide a call to terminate the IR stream. The upper-level caller should decide when to terminate the stream by append `clp::ffi::ir_stream::cProtocol::Eof` at the end of the stream.

# Validation performed

- Added a unit test case to ensure the serializer can be successfully created with the preamble section serialized properly; also tested to ensure it can properly serialize a UTC offset change.
- Passsed `clang-tidy` checks for the `Serializer` implementation.
- Didn't execute `clang-tidy` against the unit test file since it is not synchronized with the latest coding guideline.

2024-06-21 18:46 UTC, gibber9809 submitted a review, later dismissed
LGTM. How about "ffi: Add Serializer class for new IR stream format." for the title?

2024-06-21 20:07 UTC, kirkrodrigues requested changes

2024-06-21 20:07 UTC, kirkrodrigues commented on components/core/tests/test-ir_encoding_methods.cpp
> +        std::vector<int8_t>& byte_buf
Add `#include <vector>`

2024-06-21 20:07 UTC, kirkrodrigues commented on components/core/tests/test-ir_encoding_methods.cpp
> +    // expected.
```suggestion
    // This is a unit test for the kv-pair IR serializer. Currently, we haven't yet implemented a
    // deserializer, so we can only test whether the preamble packet is serialized correctly.
```

2024-06-21 20:07 UTC, kirkrodrigues commented on components/core/src/clp/ffi/ir_stream/Serializer.hpp
> +     * - std::errc::protocol_error if failed to serialize the preamble.
```suggestion
     * - std::errc::protocol_error on failure to serialize the preamble.
```

2024-06-21 20:07 UTC, kirkrodrigues commented on components/core/src/clp/ffi/ir_stream/Serializer.hpp
> +     * @return A view to the underlying IR buffer which contains the serialized IR bytes.
```suggestion
     * @return A view of the underlying IR buffer which contains the serialized IR bytes.
```

2024-06-21 20:07 UTC, kirkrodrigues commented on components/core/src/clp/ffi/ir_stream/Serializer.hpp
> +     * buffer if the given UTC offset is different with the current UTC offset.
```suggestion
     * Changes the UTC offset and serializes a UTC offset change packet, if the given UTC offset is
     * different than the current UTC offset.
```

2024-06-22 08:51 UTC, kirkrodrigues approved these changes
> LGTM. How about "ffi: Add Serializer class for new IR stream format." for the title?

How about a slight update:

ffi: Add WIP Serializer class for the next IR stream format.

2024-06-22 20:49 UTC, LinZhihao-723 commented
> > LGTM. How about "ffi: Add Serializer class for new IR stream format." for the title?
> 
> How about a slight update:
> 
> ffi: Add WIP Serializer class for the next IR stream format.

lgtm

2024-06-22 20:50 UTC, merged