Implement translator logic to translate regex character sets into wildcards by attempting to reduce them to a single characters.
y-scope/clp pull request #493
Opened 2024-07-25 05:38 UTC by Bill-hbrhbr

# Description
Implements the following functionality:
  * Reduces a character set into a single character if possible.
    * A trivial character set containing a single character or a single escaped metacharacter.
      * E.g. `[a]` into `a`, `[\^]` into `^`
    * If the `case_insensitive_wildcard` config is turned on, the translator can also reduce the
      case-insensitive style character set patterns into a single lowercase character:
      * E.g. `[aA]` into `a`, `[Bb]` into `b`, `[xX][Yy][zZ]` into `xyz`

# Validation performed
Verified in unit tests

2024-07-25 07:42 UTC, LinZhihao-723 requested changes
Before going to the detailed review, I had some comments about the way of tracking the charset. In the current implementation, we have an iterator in the `TranslatorState` and expose APIs to update/query the underlying iterator that points to the beginning of the charset. However, it's a little confusing and unsafe:
1. The constructor also takes an iterator, which doesn't make sense if it is not the beginning of the charset.
2. The names of `m_it`, `get_marked_iterator`, and `mark_iterator` don't really indicate their usage.
3. When querying an iterator, we don't have a sanity check of whether it is set to the beginning of a charset properly.

I would propose a solution which we can add a dedicated class to track the status of charset escape. It should have a counter of chars processed (indicating the length of the charset), a flag indicating whether it's an escape char or not, and also the storage of the character to proceed. The `TranslatorState` should have a `std::optional` member of such a charset status tracker, and emplace the optional tracker when `[` is found and reset the optional tracker when `]` is found. All the checks can be passed down to the charset tracker's member function to proceed when you see the character in `charset_state_transition`, and you don't need the chaining `if-else` with the length check. Defininig sub-states inside this charset tracker class might be useful. I think that would make the interface more clean and readable.

2024-07-26 05:09 UTC, davidlion requested changes

2024-07-26 05:09 UTC, davidlion commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> +            // 2-char escape sequence
```suggestion
```

2024-07-26 05:09 UTC, davidlion commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> + * precedence over UnsupportedCharsetPattern.
```suggestion
* On error returns either IncompleteCharsetStructure or UnsupportedCharsetPattern.
```

2024-07-26 05:09 UTC, davidlion commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> +            // case-insensitive patterns like [aA] [Bb] etc.
```suggestion
```

2024-07-28 03:47 UTC, LinZhihao-723 requested changes

2024-07-28 03:47 UTC, LinZhihao-723 commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> +    optional<string_view::const_iterator> m_charset_start{nullopt};
```suggestion
    optional<string_view::const_iterator> m_charset_start;
```
You can rely on the default constructor

2024-07-28 03:47 UTC, LinZhihao-723 commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> +    optional<string_view::const_iterator> m_charset_start{nullopt};
How about `m_charset_start_it`?

2024-07-28 03:47 UTC, LinZhihao-723 commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> +    auto invalidate_charset_start() -> void { m_charset_start = nullopt; }
```suggestion
    auto invalidate_charset_start() -> void { m_charset_start.reset(); }
```

2024-07-28 03:47 UTC, LinZhihao-723 commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> +    string_view::const_iterator const charset_start = charset_start_opt.value();
```suggestion
    auto const charset_start = charset_start_opt.value();
```

2024-07-28 03:47 UTC, LinZhihao-723 commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> +            break;
Do we need `break` after return?

2024-07-28 03:47 UTC, LinZhihao-723 commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> +// Other helpers
Not necessary
```suggestion
```

2024-07-28 03:47 UTC, LinZhihao-723 commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> + * @return True if the input is a matching pair.
```suggestion
 * @return Whether the input chars are a matching pair.
```

2024-07-28 03:47 UTC, LinZhihao-723 commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> +inline auto append_char_to_wildcard(char const ch, string& wildcard_str) -> void {
```suggestion
auto append_char_to_wildcard(char const ch, string& wildcard_str) -> void {
```
1. We don't explicitly add `inline` unless the profiling shows a different on performance
2. We should put helper declarations at the top and move the actual implementation to the bottom, inside the anon namespace.

2024-07-28 03:47 UTC, LinZhihao-723 commented on components/core/src/clp/regex_utils/regex_translation_utils.cpp
> +inline auto matching_upper_lower_case_char_pair(char const ch0, char const ch1) -> bool {
```suggestion
[[nodiscard]] auto matching_upper_lower_case_char_pair(char const ch0, char const ch1) -> bool {
```

2024-07-30 05:06 UTC, davidlion approved these changes

2024-07-30 05:08 UTC, LinZhihao-723 approved these changes

2024-07-30 05:12 UTC, merged