core-clp: Add template class for CLP-encoded strings.
y-scope/clp pull request #495
Opened 2024-07-26 05:11 UTC by LinZhihao-723

# Description

This PR adds a class to wrap the CLP-encoded strings. In specific, a CLP-encoded string contains a logtype, a vector of dictionary variables, and a vector of encoded variables. The size of each encoded variable depends on the encoding type, which is either eight byte encoding or four byte encoding.
With this class, we can now split the members of `clp::ir::LogEvent` more clearly: timestamp info `m_timestamp`, timezone info `m_utc_offset`, and the actual log message `m_message`.
In the coming PRs, this class will be used to stored deserialized CLP-encoded strings when deserializing a key-value pair format CLP IR.

# Validation performed

Ensure all unit tests passed after updating `clp::ir::LogEvent` to contain `ClpString`.

2024-07-26 14:17 UTC, haiqi96 commented
I don't see any obvious issue, but the class name ClpString maybe confusing? technically what you are storing in it is not a string, but a log event without a timestamp.  Can't think of a much better name though, maybe LogEventString?

2024-07-28 04:48 UTC, LinZhihao-723 commented
> I don't see any obvious issue, but the class name ClpString maybe confusing? technically what you are storing in it is not a string, but a log event without a timestamp. Can't think of a much better name though, maybe LogEventString?

Also talked to Kirk offline and he had the similar concern. A little background: the reason why we need this is because strings are represented as either a raw string or a CLP encoded string (logtype + variables) in `clp-s`. This is the same for key-value pair IR format. So strictly speaking, this string isn't a `LogEventString` since it's just a value stored in a key-value pair record in key-value pair IR format context. I think maybe `ClpEncodedString` can be a better terminology for this case? Waiting for Kirk's comments @kirkrodrigues

2024-07-28 10:34 UTC, kirkrodrigues commented
According to our glossary, `ClpString` is actually supposed to be called `Ir` (i.e., CLP's internal representation). However, that doesn't cover our new IR for kv-pairs. Let's discuss a new naming scheme offline with David.

2024-07-29 19:13 UTC, kirkrodrigues requested changes

2024-07-30 20:41 UTC, kirkrodrigues approved these changes
For the PR title, how about:

core-clp: Add `EncodedTextAst` class to represent parsed and encoded unstructured text strings.

2024-07-30 22:39 UTC, merged